# Generated by Django 3.0.8 on 2020-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCarruselChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', models.TextField(verbose_name='Combo_1')),
                ('offer_2', models.TextField(verbose_name='Combo_2')),
                ('offer_3', models.TextField(verbose_name='Combo_3')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
