# Generated by Django 3.0.8 on 2020-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCarruselChildren2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', models.TextField(verbose_name='Combo_1')),
                ('offer_2', models.TextField(verbose_name='Combo_2')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfferCarruselChildren3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', models.TextField(verbose_name='Paquete Fine Art')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfferCarruselChildren4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', models.TextField(verbose_name='Combo_1')),
                ('offer_2', models.TextField(verbose_name='Combo_2')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfferCarruselChildren5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', models.TextField(verbose_name='Combo_1')),
                ('offer_2', models.TextField(verbose_name='Combo_2')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfferCarruselChildren6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', models.TextField(verbose_name='Paquete Familiar')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.RemoveField(
            model_name='offercarruselchildren',
            name='offer_3',
        ),
    ]
