# Generated by Django 3.0.8 on 2020-10-21 01:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200926_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offercarruselchildren',
            options={'verbose_name': 'Carrusel y Oferta', 'verbose_name_plural': 'Newborn'},
        ),
        migrations.AlterModelOptions(
            name='offercarruselchildren2',
            options={'verbose_name': 'Carrusel y Oferta', 'verbose_name_plural': 'Mini baby'},
        ),
        migrations.AlterModelOptions(
            name='offercarruselchildren3',
            options={'verbose_name': 'Carrusel y Oferta', 'verbose_name_plural': 'Fine Art '},
        ),
        migrations.AlterModelOptions(
            name='offercarruselchildren4',
            options={'verbose_name': 'Carrusel y Oferta', 'verbose_name_plural': 'Hermanitos'},
        ),
        migrations.AlterModelOptions(
            name='offercarruselchildren5',
            options={'verbose_name': 'Carrusel y Oferta', 'verbose_name_plural': 'Maternidad'},
        ),
        migrations.AlterModelOptions(
            name='offercarruselchildren6',
            options={'verbose_name': 'Carrusel y Oferta', 'verbose_name_plural': 'Familia'},
        ),
        migrations.AlterField(
            model_name='offercarruselchildren',
            name='offer_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren',
            name='offer_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
    ]
