# Generated by Django 3.0.8 on 2020-10-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20201020_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercarruselchildren2',
            name='offer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren2',
            name='offer_2',
            field=models.TextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren3',
            name='offer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Paquete Fine Art'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren4',
            name='offer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren4',
            name='offer_2',
            field=models.TextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren5',
            name='offer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren5',
            name='offer_2',
            field=models.TextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren6',
            name='offer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Paquete Familiar'),
        ),
    ]
