# Generated by Django 3.0.8 on 2020-12-11 20:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20201020_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navidad2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='category', verbose_name='Imagen 1')),
                ('image_2', models.ImageField(upload_to='category', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(upload_to='category', verbose_name='Imagen 3')),
                ('offer_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_1')),
                ('offer_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_2')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel y Oferta',
                'verbose_name_plural': 'Navidad',
            },
        ),
        migrations.AlterField(
            model_name='offercarruselchildren2',
            name='offer_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren2',
            name='offer_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren3',
            name='offer_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Paquete Fine Art'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren4',
            name='offer_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren4',
            name='offer_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren5',
            name='offer_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_1'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren5',
            name='offer_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Combo_2'),
        ),
        migrations.AlterField(
            model_name='offercarruselchildren6',
            name='offer_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Paquete Familiar'),
        ),
    ]
